spring:
    datasource:
        generate-unique-name: false
        name: kebabcloud
    thymeleaf:
        cache: false
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: <facebook client id> #application not registered on facebook yet
                        client-secret: <facebook client secret>
                        scope: email, public_profile

            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:9000/oauth2/jwks
    data:
        rest:
            base-path: /data-api
server:
    port: 8080

logging:
    file:
      path: /var/logs/
      name: KebabCloud.log
    level:
        root: info
        org.springframework.security: DEBUG

kebab:
  orders:
      page-size: 10
