spring:
    datasource:
        generate-unique-name: false
        name: kebabcloud
    thymeleaf:
        cache: false
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: <facebook client id>
                        client-secret: <facebook client secret>
                        scope: email, public_profile